### ISSUE TITLE
Error: $ROOT_URL, if specified, must be an URL

### ISSUE THREAD

**Issue by atomdmac** [wekan/wekan-mongodb#4]
After creating the `wekan` user, adding them to the `docker` group and trying `docker-compose up`, the following output is generated:

```
wekan-app  | Error: $ROOT_URL, if specified, must be an URL
wekan-app  |     at Error (native)
wekan-app  |     at packages/meteor.js:1218:13
wekan-app  |     at packages/meteor.js:1233:4
wekan-app  |     at packages/meteor.js:1380:3
wekan-app  |     at /build/programs/server/boot.js:303:34
wekan-app  |     at Array.forEach (native)
wekan-app  |     at Function._.each._.forEach (/build/programs/server/node_modules/underscore/underscore.js:79:11)
wekan-app  |     at /build/programs/server/boot.js:128:5
wekan-app  |     at /build/programs/server/boot.js:352:5
wekan-app  |     at Function.run (/build/programs/server/profile.js:510:12)
```

I have changed `ROOT_URL` in `docker-compose.yml` to the IP of my Digital Ocean droplet instance.  I have also tried changing the `ports` value for the `wekan` container to `8080:80` in case the port was blocked due to permissions.

Am I missing something obvious?

**Comment by atomdmac** [comment]
I was able to fix this by removing the single quotes from around the ROOT_URL value.  Is there a reason the single quotes are there?  I'm happy to submit a pull request for this :P
